# Direct Preference Optimization
name: tdpo

# the temperature parameter for DPO; lower values mean we care less about the reference model
beta: 0.1

trainer: TDPOTrainer

dataloader: PairedPreferenceDataLoader

use_reference_model: true